### PR TITLE
Proofreading fixes part 6 0x05c

### PR DESCRIPTION
**Pull request by Laancelot**
Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

### CODE REVIEW

**Comment by Laancelot** [comment]
line 2000 @cpholguera that section doesn't exist anymore

**Comment by Laancelot** [comment]
line 1623 @cpholguera I would replace the link with https://github.com/rovo89/XposedExamples or https://github.com/rovo89/XposedTool

**Comment by Laancelot** [comment]
@cpholguera line 2269 we might want to update the comment about Lollilop and Marshmallow - there are newer Android versions

**Comment by Laancelot** [comment]
@cpholguera line 2271 we might want to rephrase the "I recommend" line

**Comment by cpholguera** [comment]
> line 1623 @cpholguera I would replace the link with https://github.com/rovo89/XposedExamples or https://github.com/rovo89/XposedTool

You're right. Let's go with https://github.com/rovo89/XposedTools

**Comment by cpholguera** [comment]
> line 2000 @cpholguera that section doesn't exist anymore

Let's remove the whole line, it's not really adding value to the section.

**Review by cpholguera — CHANGES_REQUESTED** [review]
Please take a look at the suggestions. Thank you @Laancelot

**Comment by cpholguera** [comment]
Unfortunately I'm not able to enter suggestions for lines 1623 and 2000. Please take a look at my comments above.

**Comment by Laancelot** [comment]
it's done; sorry for the delay @cpholguera

**Review by cpholguera — APPROVED** [review]
No problem @Laancelot, thank you very much for the corrections!

**Pull request merged**
