### PR TITLE
Add Risk and Test - Backup Unencrypted [backup-unencrypted]

### LINKED ISSUE #2541: New Risk - Backup Unencrypted [backup-unencrypted]
## Description

Create a new risk for "Backup Unencrypted (MASVS-STORAGE-2)" using the following information:

The app may not encrypt sensitive data in backups, which may compromise data confidentiality.

Create "`risks/MASVS-STORAGE/2-***-****/backup-unencrypted/risk.md`" including the following content:

```yaml
---
title: Backup Unencrypted
alias: backup-unencrypted
platform: [android]
profiles: [L2]
mappings:
- masvs-v1: [MSTG-STORAGE-8]
- masvs-v2: [MASVS-STORAGE-2, MASVS-PRIVACY-1]

---

## Overview

## Impact

## Modes of Introduction

## Mitigations

```

**To complete the sections follow the guidelines from [Writing MASTG Risks & Tests](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)**

Use at least the following references:

- <https://developer.android.com/guide/topics/data/autobackup#define-device-conditions>

When creating the corresponding test, use the following areas to guide you:

- Backup Device Conditions clientSideEncryption and deviceToDeviceTransfer Not Checked (Android)

**MASTG v1 Refactoring:**

If the risk has a MASVS v1 ID, you can use it to [search for related tests in the MASTG](https://mas.owasp.org/MASTG/tests/) and use them as input to define your risks and associated tests.
Include the related MASTG v1 tests in the metadata of the risk. For example:

```yaml
mappings:
- mastg-v1: [MASTG-TEST-11]
```

## Acceptance Criteria

- [ ] The risk has been created in the correct directory (`risks/MASVS-STORAGE/2-***-****/backup-unencrypted/risk.md`)
- [ ] The risk content follows the [guidelines](https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing)
- [ ] At least one GitHub Issue has been created for the corresponding tests (derived from "Modes of Introduction")
- [ ] The risk indicates the related MASTG v1 tests in its metadata.

### PR DESCRIPTION
**Pull request by e-a-security**
This PR closes #2541.

### CODE REVIEW

**Comment by cpholguera** [comment]
Updated title and linking to issue in description (using the "closes #2541" statement).

**Comment by cpholguera** [comment]
Thanks for opening the PR @e-a-security! Here's some initial feedback to comply with our structure and guidelines. We'll do a more in-depth tech review after all this is fixed.

- Remove any `README.md` files you have (you may be able to reuse the info in those files to create the missing `test.md` and `example.md` files, see below)
- Add `test.md` files under each folder:
  - `android-backup-unencrypted/test.md`
  - `ios-backup-unencrypted/test.md
`- Add `example.md` files and add number to the example folders:
  - `android-backup-unencrypted/example-1/example.md`
  - `ios-backup-unencrypted/example-1/example.md`
- Fix the metadata in risk.md file, see the [GitHub issue](https://github.com/OWASP/owasp-mastg/issues/2541). This is called "yaml frontmatter" and is used in markdown files to enter metadata. It must follow the provided syntax including those `---` delimiters and lowercase keys.
- Rules have some predefined metadata, including a "summary" field which you can use to enter the description of each rule instead of using a `README.md` file. See one example [here](https://github.com/OWASP/owasp-mastg/blob/master/risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/rules/mastg-android-non-random-use.yaml)

See all guidelines here: https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing 

At the beginning of that document you can find links to existing risks and tests so you can follow the same structure. If you still have questions after looking into that please let me know.

**Review by cpholguera — CHANGES_REQUESTED** [review]
Thanks for opening the PR @e-a-security! Here's some initial feedback to comply with our structure and guidelines. We'll do a more in-depth tech review after all this is fixed.

- Remove any `README.md` files you have (you may be able to reuse the info in those files to create the missing `test.md` and `example.md` files, see below)
- Add `test.md` files under each folder:
  - `android-backup-unencrypted/test.md`
  - `ios-backup-unencrypted/test.md
`- Add `example.md` files and add number to the example folders:
  - `android-backup-unencrypted/example-1/example.md`
  - `ios-backup-unencrypted/example-1/example.md`
- Fix the metadata in risk.md file, see the [GitHub issue](https://github.com/OWASP/owasp-mastg/issues/2541). This is called "yaml frontmatter" and is used in markdown files to enter metadata. It must follow the provided syntax including those `---` delimiters and lowercase keys.
- Rules have some predefined metadata, including a "summary" field which you can use to enter the description of each rule instead of using a `README.md` file. See one example [here](https://github.com/OWASP/owasp-mastg/blob/master/risks/MASVS-CRYPTO/1-strong-crypto/insecure-random/android-non-random-use/rules/mastg-android-non-random-use.yaml)

See all guidelines here: https://docs.google.com/document/d/1EMsVdfrDBAu0gmjWAUEs60q-fWaOmDB5oecY9d9pOlg/edit?usp=sharing 

At the beginning of that document you can find links to existing risks and tests so you can follow the same structure. If you still have questions after looking into that please let me know.

**Comment by sushi2k** [comment]
Hi @e-a-security! Can you please let us know when you can continue to work on this or do you have a timeline for it? Thanks

**Comment by cpholguera** [comment]
Elias can unfortunately not continue with this PR so we'll close it and assign the issue to another person.

**Pull request closed without merging**
