### PR TITLE
#2295 [MSTG-CODE-2] Add a static analysis method (codesign/ldid)

### LINKED ISSUE #2295: [MSTG-CODE-2] Add a static analysis method for get-task-allow
### Discussed in https://github.com/OWASP/owasp-mastg/discussions/2294

<div type='discussions-op-text'>

<sup>Originally posted by **sohsatoh** October 21, 2022</sup>
Currently, the static analysis section of MSTG-CODE-2 for iOS only describes methods for those who can access to the source code.

However, there is a way to check that `get-task-allow` is true in the entitlement using ldid.

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues?language=objc

Any thoughts on adding this to the Static Analysis section?

(I wasn't sure whether I could submit a pull request directly, so I posted here.)</div>

### PR DESCRIPTION
**Pull request by sohsatoh**
Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #2295

### CODE REVIEW

**Comment by sohsatoh** [comment]
As I am not a native speaker of English, it would be great if you could tell me if I have made any mistakes in English grammar or something.

**Comment by cpholguera** [comment]
Thank you very much for taking the time to open this PR @sohsatoh!

**Review by cpholguera — CHANGES_REQUESTED** [review]
Hi @sohsatoh, thanks for including this. This is exactly what this test case needed!

Could you please also apply the following changes? This way we keep the mitigation part in the overview and the static analysis will only contain what you've added (using codesign and using ldid).

```
## Determining Whether the App is Debuggable (MSTG-CODE-2)

### Overview

To test if the app is [debugging](0x06c-Reverse-Engineering-and-Tampering.md#debugging) you need to inspect the app entitlements and check if the value of [`get-task-allow`](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues, "Resolving common notarization issues") key is set to `true`.

While debugging is a useful feature when developing an app, it has to be turned off before releasing apps to the App Store or within an enterprise program. To do that you need to determine the mode in which your app is to be generated to check the flags in the environment:

- Select the build settings of the project
- Under 'Apple LVM - Preprocessing' and 'Preprocessor Macros', make sure 'DEBUG' or 'DEBUG_MODE' is not selected (Objective-C)
- Make sure that the "Debug executable" option is not selected.
- Or in the 'Swift Compiler - Custom Flags' section / 'Other Swift Flags', make sure the '-D DEBUG' entry does not exist.

### Static Analysis


```

**Review by sushi2k — APPROVED** [review]

**Review by cpholguera — APPROVED** [review]
Thanks a lot @sohsatoh!

**Pull request merged**
