### PR TITLE
Proofreading fixes part 2 0x05c

### PR DESCRIPTION
**Pull request by Laancelot**
Thank you for submitting a Pull Request to the OWASP MASTG. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

### CODE REVIEW

**Comment by Laancelot** [comment]
the graph at line 424 looks completely messed up; is that normal?

**Comment by cpholguera** [comment]
@Laancelot I can't find any graph in 424, is that the right line number?

**Comment by Laancelot** [comment]
@cpholguera this is the block of code

`The function table is initialized by the Java VM and allows the native function to interact with the Java environment.

With that in mind, let's have a look at each line of assembly code.
`

**Comment by cpholguera** [comment]
This is it, right? What do you think it's wrong about it?

**Comment by Laancelot** [comment]
ah - I suspected it should look something like this @cpholguera 
this is how it shows up on my end and I have no idea why
Screenshot 2022-11-02 at 9 40 28 am

**Review by cpholguera — APPROVED** [review]
Thank you @Laancelot!

**Pull request merged**
